// Verbex format converters — pure functions, no DOM.
//
// segments: [{ start: seconds, end: seconds, text }]
// meta:     { title, channel, url, videoId, language, isAuto }
// chapters: [{ title, start: seconds }]
// opts:     { includeTimestamps, granularity, includeChapterMarkers }

function pad(n, w = 2) { return String(n).padStart(w, '0'); }

export function fmtTimestamp(sec) {
  const s = Math.max(0, Math.floor(sec));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const r = s % 60;
  if (h > 0) return `${pad(h)}:${pad(m)}:${pad(r)}`;
  return `${pad(m)}:${pad(r)}`;
}

function fmtSrtTimestamp(sec) {
  const total = Math.max(0, sec);
  const ms = Math.floor((total % 1) * 1000);
  const s = Math.floor(total);
  return `${pad(Math.floor(s / 3600))}:${pad(Math.floor((s % 3600) / 60))}:${pad(s % 60)},${pad(ms, 3)}`;
}

// Collapse segments based on granularity. Returns same shape.
function applyGranularity(segments, granularity, chapters) {
  if (!segments.length || granularity === 'every-line') return segments;

  if (granularity === 'chapter-only') {
    if (!chapters || !chapters.length) return collapseByInterval(segments, 9999999);
    const sorted = [...chapters].sort((a, b) => a.start - b.start);
    const groups = [];
    for (let i = 0; i < sorted.length; i++) {
      const start = sorted[i].start;
      const end = i + 1 < sorted.length ? sorted[i + 1].start : Infinity;
      const chunk = segments.filter((s) => s.start >= start && s.start < end);
      if (!chunk.length) continue;
      groups.push({
        start: chunk[0].start,
        end: chunk[chunk.length - 1].end,
        text: chunk.map((s) => s.text).join(' '),
      });
    }
    return groups.length ? groups : segments;
  }

  const interval = granularity === 'every-30s' ? 30 : 10;
  return collapseByInterval(segments, interval);
}

function collapseByInterval(segments, interval) {
  if (!segments.length) return segments;
  const out = [];
  let bucket = null;
  for (const s of segments) {
    const slot = Math.floor(s.start / interval);
    if (!bucket || bucket.slot !== slot) {
      if (bucket) out.push(bucket);
      bucket = { slot, start: s.start, end: s.end, text: s.text };
    } else {
      bucket.end = s.end;
      bucket.text += ' ' + s.text;
    }
  }
  if (bucket) out.push(bucket);
  return out;
}

function autoNote(meta) {
  return meta.isAuto
    ? '\n--- Captions: auto-generated by YouTube. Accuracy may vary.\n'
    : '';
}

export function toTxt(segments, meta, chapters = [], opts = {}) {
  const o = { includeTimestamps: true, granularity: 'every-line', includeChapterMarkers: true, ...opts };
  const lines = [];
  lines.push(meta.title || 'Untitled');
  lines.push(meta.channel || '');
  if (meta.url) lines.push(meta.url);
  lines.push('');

  const segs = applyGranularity(segments, o.granularity, chapters);
  const chapStarts = o.includeChapterMarkers && chapters?.length
    ? chapters.map((c) => ({ ...c, used: false })).sort((a, b) => a.start - b.start)
    : [];

  for (const s of segs) {
    if (chapStarts.length) {
      const ch = chapStarts.find((c) => !c.used && c.start <= s.start);
      if (ch) {
        if (lines[lines.length - 1] !== '') lines.push('');
        lines.push(`## ${ch.title} [${fmtTimestamp(ch.start)}]`);
        lines.push('');
        ch.used = true;
      }
    }
    const text = (s.text || '').replace(/\s+/g, ' ').trim();
    if (!text) continue;
    if (o.includeTimestamps) {
      lines.push(`[${fmtTimestamp(s.start)}] ${text}`);
    } else {
      lines.push(text);
    }
  }
  lines.push('');
  lines.push(autoNote(meta).trim());
  return lines.join('\n').replace(/\n{3,}/g, '\n\n');
}

export function toSrt(segments, meta, chapters = [], opts = {}) {
  const o = { includeChapterMarkers: true, ...opts };
  const out = [];
  let idx = 1;
  const chapStarts = o.includeChapterMarkers && chapters?.length
    ? chapters.map((c) => ({ ...c, used: false })).sort((a, b) => a.start - b.start)
    : [];

  for (const s of segments) {
    if (chapStarts.length) {
      const ch = chapStarts.find((c) => !c.used && c.start <= s.start);
      if (ch) {
        out.push(`NOTE Chapter — ${ch.title}\n`);
        ch.used = true;
      }
    }
    const text = (s.text || '').replace(/\s+/g, ' ').trim();
    if (!text) continue;
    const end = s.end > s.start ? s.end : s.start + 2;
    out.push(`${idx}\n${fmtSrtTimestamp(s.start)} --> ${fmtSrtTimestamp(end)}\n${text}\n`);
    idx += 1;
  }
  return out.join('\n');
}

export function toMarkdown(segments, meta, chapters = [], opts = {}) {
  const o = { includeTimestamps: true, granularity: 'every-line', includeChapterMarkers: true, ...opts };
  const lines = [];
  lines.push(`# ${meta.title || 'Untitled'}`);
  lines.push('');
  if (meta.channel) lines.push(`**Channel:** ${meta.channel}  `);
  if (meta.url) lines.push(`**URL:** ${meta.url}  `);
  lines.push(`**Exported:** ${new Date().toISOString().slice(0, 10)}`);
  lines.push('');

  const segs = applyGranularity(segments, o.granularity, chapters);
  const chapStarts = o.includeChapterMarkers && chapters?.length
    ? chapters.map((c) => ({ ...c, used: false })).sort((a, b) => a.start - b.start)
    : [];

  if (chapStarts.length) {
    for (let i = 0; i < chapStarts.length; i++) {
      const ch = chapStarts[i];
      const next = chapStarts[i + 1]?.start ?? Infinity;
      const chunk = segs.filter((s) => s.start >= ch.start && s.start < next);
      if (!chunk.length) continue;
      lines.push(`## ${i + 1} — ${ch.title} [${fmtTimestamp(ch.start)}]`);
      lines.push('');
      for (const s of chunk) {
        const text = (s.text || '').replace(/\s+/g, ' ').trim();
        if (!text) continue;
        lines.push(o.includeTimestamps ? `- \`${fmtTimestamp(s.start)}\` ${text}` : text);
      }
      lines.push('');
    }
  } else {
    for (const s of segs) {
      const text = (s.text || '').replace(/\s+/g, ' ').trim();
      if (!text) continue;
      lines.push(o.includeTimestamps ? `- \`${fmtTimestamp(s.start)}\` ${text}` : text);
    }
  }

  if (meta.isAuto) {
    lines.push('');
    lines.push('---');
    lines.push('_Captions auto-generated by YouTube. Accuracy may vary._');
  }
  return lines.join('\n').replace(/\n{3,}/g, '\n\n');
}

export function toClipboardText(segments, meta, chapters, opts) {
  return toTxt(segments, meta, chapters, opts);
}

export function wordCount(segments) {
  return segments.reduce((sum, s) => sum + (s.text ? s.text.trim().split(/\s+/).length : 0), 0);
}

export function extForFormat(fmt) {
  return fmt === 'md' ? 'md' : fmt === 'srt' ? 'srt' : 'txt';
}

export function mimeForFormat(fmt) {
  if (fmt === 'srt') return 'text/plain;charset=utf-8';
  if (fmt === 'md') return 'text/markdown;charset=utf-8';
  return 'text/plain;charset=utf-8';
}
